# Generated by Django 4.0.3 on 2022-03-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='BlogProject',
        ),
    ]
