# Generated by Django 4.0.3 on 2022-03-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_blogproject_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogproject',
            name='description',
            field=models.TextField(default='Description'),
        ),
    ]
