# Generated by Django 4.0.3 on 2022-03-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_blogproject_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogproject',
            name='url',
        ),
    ]
