# Generated by Django 4.0.3 on 2022-03-28 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_blogproject_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogproject',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 28, 11, 35, 47, 634616, tzinfo=utc)),
        ),
    ]
