# Generated by Django 4.0.3 on 2022-03-28 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_blogproject_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogproject',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 28, 11, 48, 48, 915721, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blogproject',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 28, 11, 48, 48, 915750, tzinfo=utc)),
        ),
    ]
