# Generated by Django 4.0.3 on 2022-04-05 11:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_blogproject_date_alter_blogproject_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.datetime(2022, 4, 5, 11, 51, 15, 128419, tzinfo=utc))),
                ('time', models.TimeField(default=datetime.datetime(2022, 4, 5, 11, 51, 15, 128445, tzinfo=utc))),
                ('description', models.TextField(default='Description')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogProject',
        ),
    ]
