# Generated by Django 4.0.3 on 2022-04-05 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_cardproject_delete_blogproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardproject',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 5, 11, 53, 40, 868222, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cardproject',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 5, 11, 53, 40, 868248, tzinfo=utc)),
        ),
    ]
