# Generated by Django 4.0.3 on 2022-04-05 11:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_cardproject_date_alter_cardproject_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardproject',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 5, 11, 58, 20, 867390, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cardproject',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 5, 11, 58, 20, 867416, tzinfo=utc)),
        ),
    ]
