# Generated by Django 4.0.3 on 2022-04-05 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_cardproject_date_alter_cardproject_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardproject',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cardproject',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
