# Generated by Django 4.0.3 on 2022-04-05 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_cardproject_date_alter_cardproject_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardproject',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='home/media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardproject',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
