# Generated by Django 4.0.3 on 2022-04-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_cardproject_image_cardproject_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardproject',
            name='image',
            field=models.ImageField(upload_to='portfolio/images/'),
        ),
    ]
