# Generated by Django 4.0.3 on 2022-04-10 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_cardproject_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardproject',
            old_name='image',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='cardproject',
            name='res1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='portfolio/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardproject',
            name='res1_descr',
            field=models.TextField(default='Result1 Description'),
        ),
        migrations.AddField(
            model_name='cardproject',
            name='res2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='portfolio/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardproject',
            name='res2_descr',
            field=models.TextField(default='Result2 Description'),
        ),
        migrations.AddField(
            model_name='cardproject',
            name='res3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='portfolio/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardproject',
            name='res3_descr',
            field=models.TextField(default='Result3 Description'),
        ),
    ]
