# Generated by Django 4.0.3 on 2022-04-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_cardproject_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardproject',
            name='report',
            field=models.FileField(default='nothing', upload_to='portfolio/docs/'),
        ),
        migrations.AlterField(
            model_name='cardproject',
            name='res1',
            field=models.ImageField(default='nothing', upload_to='portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='cardproject',
            name='res2',
            field=models.ImageField(default='nothing', upload_to='portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='cardproject',
            name='res3',
            field=models.ImageField(default='nothing', upload_to='portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='cardproject',
            name='video',
            field=models.FileField(default='nothing', upload_to='portfolio/docs/'),
        ),
    ]
