# Generated by Django 4.0.3 on 2022-04-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_alter_cardproject_report_alter_cardproject_res1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardproject',
            name='logo',
            field=models.ImageField(default='nothing', upload_to='portfolio/images/'),
        ),
    ]
