# Generated by Django 4.0.3 on 2022-04-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_alter_cardproject_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardproject',
            name='video_head',
            field=models.TextField(default='Video Head Description'),
        ),
        migrations.AddField(
            model_name='cardproject',
            name='video_lead',
            field=models.TextField(default='Video Lead Description'),
        ),
        migrations.AddField(
            model_name='cardproject',
            name='video_span',
            field=models.TextField(default='Video Span Description'),
        ),
        migrations.AlterField(
            model_name='cardproject',
            name='res1_head',
            field=models.TextField(default='Res1 Head Description'),
        ),
        migrations.AlterField(
            model_name='cardproject',
            name='res1_lead',
            field=models.TextField(default='Res1 Lead Description'),
        ),
        migrations.AlterField(
            model_name='cardproject',
            name='res1_span',
            field=models.TextField(default='Res1 Span Description'),
        ),
        migrations.AlterField(
            model_name='cardproject',
            name='res2_head',
            field=models.TextField(default='Res2 Head Description'),
        ),
        migrations.AlterField(
            model_name='cardproject',
            name='res2_lead',
            field=models.TextField(default='Res2 Lead Description'),
        ),
        migrations.AlterField(
            model_name='cardproject',
            name='res2_span',
            field=models.TextField(default='Res2 Span Description'),
        ),
        migrations.AlterField(
            model_name='cardproject',
            name='res3_head',
            field=models.TextField(default='Res3 Head Description'),
        ),
        migrations.AlterField(
            model_name='cardproject',
            name='res3_lead',
            field=models.TextField(default='Res3 Lead Description'),
        ),
        migrations.AlterField(
            model_name='cardproject',
            name='res3_span',
            field=models.TextField(default='Res3 Span Description'),
        ),
    ]
