# Generated by Django 4.0.3 on 2022-04-11 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_cardproject_video_head_cardproject_video_lead_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardproject',
            old_name='url',
            new_name='github',
        ),
    ]
